Add periodical check to make sure slurmd and slurmctld is started.

diff --git a/slurm/slurmsinglenode/output/batch_job.yaml b/slurm/slurmsinglenode/output/batch_job.yaml
--- a/slurm/slurmsinglenode/output/batch_job.yaml
+++ b/slurm/slurmsinglenode/output/batch_job.yaml
@@ -77,8 +77,18 @@ taskGroups:
           touch /var/log/slurm_jobacct.log /var/log/slurm_jobcomp.log
 
           systemctl restart slurmd
-          sleep 1
           systemctl restart slurmctld
-          sleep 2
+          MAX_RETRIES=5
+          RETRY_INTERVAL=5
+          for (( i=1; i<=MAX_RETRIES; i++ )); do
+              if systemctl is-active --quiet slurmd && systemctl is-active --quiet slurmctld; then
+                  echo "Both slurmd and slurmctld are running."
+                  exit 0
+              fi
+              echo "Services not running. Retrying in $RETRY_INTERVAL seconds..."
+              sleep $RETRY_INTERVAL
+          done
+          echo "Failed to start slurmd and/or slurmctld after $MAX_RETRIES attempts."
+          exit 1
     - script:
         text: sleep 1800
